# Generated by Django 3.2.8 on 2021-10-29 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('shop', '0005_miscard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
