# Generated by Django 3.2.8 on 2021-10-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('shop', '0014_followings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followings',
            unique_together={('user', 'followed_by')},
        ),
    ]
