# Generated by Django 3.2.8 on 2021-10-31 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('shop', '0015_alter_followings_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMisCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField()),
                ('miscard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_miscards', to='shop.miscard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'unique_together': {('miscard', 'user')},
            },
        ),
    ]
