# Generated by Django 3.2.8 on 2021-10-31 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('shop', '0016_savedmiscard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmiscard',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mistake', models.TextField()),
                ('lesson', models.TextField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_user', to='core.user')),
            ],
        ),
    ]
