# Generated by Django 3.2.8 on 2021-10-31 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20211031_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='followings',
            name='follow_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
