# Generated by Django 3.2.8 on 2021-10-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_followings_follow_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscard',
            name='comment_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
